### ISSUE TITLE
ChannelDetails Crashes

### ISSUE THREAD

**Issue by RobinRMC** [Strencher/BetterDiscordStuff#107]
Since a few days ago, the plugin lets my client crash whenever I hover over a voice channel. I ignored it at first, but since today it lets my Discord crash whenever I hover over any channel.

`
Prettified stacktraces, stack:
 TypeError: ChannelDetails-tooltip-tooltip is not a constructor
    at ChannelTooltip (betterdiscord://plugins/ChannelDetails.plugin.js:440:59) 
Component stack:
     at ChannelTooltip (betterdiscord://plugins/ChannelDetails.plugin.js:416:6)
    at div
    at PatchedThreadsPopout (betterdiscord://plugins/ChannelDetails.plugin.js:887:9)
    at betterdiscord://plugins/0PluginLibrary.plugin.js:1928:73
    at div
    at v (https://discord.com/assets/9a19a2cffb2b447d1882.js:3247:663)
    at p (https://discord.com/assets/9a19a2cffb2b447d1882.js:2080:737)
    at div
    at t (https://discord.com/assets/9a19a2cffb2b447d1882.js:3473:797)
    at T (https://discord.com/assets/9a19a2cffb2b447d1882.js:3470:556)
    at AppLayer
    at t (https://discord.com/assets/9a19a2cffb2b447d1882.js:3480:344)
    at t (https://discord.com/assets/9a19a2cffb2b447d1882.js:3171:930)
    at t (https://discord.com/assets/9a19a2cffb2b447d1882.js:3244:612)
    at div
    at t (https://discord.com/assets/133be657315a84d701ae.js:1382:794)
    at y (https://discord.com/assets/9a19a2cffb2b447d1882.js:4383:134)
    at y (https://discord.com/assets/9a19a2cffb2b447d1882.js:4383:134)
    at R (https://discord.com/assets/133be657315a84d701ae.js:1385:218)
    at p (https://discord.com/assets/9a19a2cffb2b447d1882.js:2080:737)
    at div
    at div
    at betterdiscord://plugins/0PluginLibrary.plugin.js:1928:73
    at t.FocusJumpSection (https://discord.com/assets/9a19a2cffb2b447d1882.js:2067:445)
    at t (https://discord.com/assets/133be657315a84d701ae.js:1335:779)
    at E (https://discord.com/assets/9a19a2cffb2b447d1882.js:3845:702)
    at pe (https://discord.com/assets/133be657315a84d701ae.js:1347:928)
    at nav
    at t (https://discord.com/assets/141c621924a936595d90.js:1398:177)
    at ke (https://discord.com/assets/141c621924a936595d90.js:1408:484)
    at https://discord.com/assets/141c621924a936595d90.js:34:11
    at div
    at De (https://discord.com/assets/141c621924a936595d90.js:36:27)
    at div
    at div
    at div
    at ke (https://discord.com/assets/141c621924a936595d90.js:36:922)
    at div
    at l (https://discord.com/assets/9a19a2cffb2b447d1882.js:4303:605)
    at t (https://discord.com/assets/141c621924a936595d90.js:135:633)
    at div
    at t (https://discord.com/assets/9a19a2cffb2b447d1882.js:4212:854)
    at t (https://discord.com/assets/141c621924a936595d90.js:138:256)
    at x (https://discord.com/assets/141c621924a936595d90.js:139:830)
    at div
    at t (https://discord.com/assets/141c621924a936595d90.js:357:342)
    at U (https://discord.com/assets/141c621924a936595d90.js:119:440)
    at t (https://discord.com/assets/9a19a2cffb2b447d1882.js:5699:359)
    at t (https://discord.com/assets/9a19a2cffb2b447d1882.js:5701:414)
    at t (https://discord.com/assets/141c621924a936595d90.js:221:12)
    at u (https://discord.com/assets/9a19a2cffb2b447d1882.js:3980:738)
    at Suspense
    at d
    at t (https://discord.com/assets/9a19a2cffb2b447d1882.js:5699:359)
    at t (https://discord.com/assets/9a19a2cffb2b447d1882.js:5701:414)
    at div
    at O (https://discord.com/assets/9a19a2cffb2b447d1882.js:3500:397)
    at t (https://discord.com/assets/9a19a2cffb2b447d1882.js:3469:761)
    at VerificationLayerProvider
    at t (https://discord.com/assets/9a19a2cffb2b447d1882.js:3469:761)
    at AppLayerProvider
    at p (https://discord.com/assets/9a19a2cffb2b447d1882.js:2080:737)
    at t (https://discord.com/assets/9a19a2cffb2b447d1882.js:717:554)
    at m (https://discord.com/assets/9a19a2cffb2b447d1882.js:719:975)
    at t (https://discord.com/assets/9a19a2cffb2b447d1882.js:720:436)
    at u (https://discord.com/assets/9a19a2cffb2b447d1882.js:3980:738)
    at h (https://discord.com/assets/9a19a2cffb2b447d1882.js:698:564)
    at te (https://discord.com/assets/9a19a2cffb2b447d1882.js:701:731)
    at t (https://discord.com/assets/9a19a2cffb2b447d1882.js:811:541)
    at u (https://discord.com/assets/9a19a2cffb2b447d1882.js:3979:679)
    at https://discord.com/assets/9a19a2cffb2b447d1882.js:4367:30
    at F (https://discord.com/assets/9a19a2cffb2b447d1882.js:5505:700)
    at t (https://discord.com/assets/9a19a2cffb2b447d1882.js:5695:962)
    at t (https://discord.com/assets/9a19a2cffb2b447d1882.js:5644:817)
    at f (https://discord.com/assets/9a19a2cffb2b447d1882.js:2313:813)
`

**Comment by RobinRMC** [comment]
Just found out it was a compatibility issue with Channel Permissions (another plug-in).
