### ISSUE TITLE
ChannelDms - Could not be constructed

### ISSUE THREAD

**Issue by Pokesketch** [Strencher/BetterDiscordStuff#243]
Plugin doesn't work after a BetterDiscord Update.
![image](https://user-images.githubusercontent.com/62312740/182669367-8281933a-5140-4700-b284-bea5b6abd875.png)

**Comment by ksmarty** [comment]
My similar, but not identical error:

```js
ChannelDms: Could not be constructed.
at Object.initializeAddon (<anonymous>:4:306851)
at Object.loadAddon (<anonymous>:4:268341)
at Object.loadAddon (<anonymous>:4:305889)
at FSWatcher.<anonymous> (<anonymous>:4:266190)
```

**Comment by realqdbp** [comment]
I have can't be compiled.

```
TypeError: Cannot read property 'register' of undefined
    at new e (https://discord.com/assets/998d03874151e82d569a.js:4287:740)
    at new SettingsManager (betterdiscord://plugins/ChannelDms.plugin.js:439:6)
    at eval (betterdiscord://plugins/ChannelDms.plugin.js:454:21)
    at eval (betterdiscord://plugins/ChannelDms.plugin.js:994:5)
    at buildPlugin (betterdiscord://plugins/ChannelDms.plugin.js:996:4)
    at eval (betterdiscord://plugins/ChannelDms.plugin.js:1001:2)
    at Object.requireAddon (<anonymous>:4:43432)
    at Object.loadAddon (<anonymous>:4:9220)
    at Object.loadAddon (<anonymous>:4:41184)
    at Object.reloadAddon (<anonymous>:4:10081)
    at FSWatcher.<anonymous> (<anonymous>:4:7629)
```

**Comment by HypedDomi** [comment]
Fixed. Redownload from GitHub
