### ISSUE TITLE
[StatusEverywhere] Plugin could not be compiled

### ISSUE THREAD

**Issue by Tyeia** [Strencher/BetterDiscordStuff#274]
Upon plugins loading, this error pops up and statuseverywhere does not load.
`TypeError: Cannot read property 'register' of undefined
    at new e (https://discord.com/assets/3217b04777dfcd16e8cd.js:4323:387)
    at new SettingsManager (betterdiscord://plugins/StatusEverywhere.plugin.js:516:6)
    at eval (betterdiscord://plugins/StatusEverywhere.plugin.js:530:21)
    at eval (betterdiscord://plugins/StatusEverywhere.plugin.js:1731:5)
    at buildPlugin (betterdiscord://plugins/StatusEverywhere.plugin.js:1733:4)
    at eval (betterdiscord://plugins/StatusEverywhere.plugin.js:1738:2)
    at Object.requireAddon (<anonymous>:4:43095)
    at Object.loadAddon (<anonymous>:4:8859)
    at Object.loadAddon (<anonymous>:4:40847)
    at Object.updateList (<anonymous>:4:10713)
    at Object.updatePluginList (<anonymous>:4:40544)
    at O.reload (<anonymous>:4:108624)
    at Object.Ye (https://discord.com/assets/3217b04777dfcd16e8cd.js:6016:658)
    at qe (https://discord.com/assets/3217b04777dfcd16e8cd.js:6016:812)
    at https://discord.com/assets/3217b04777dfcd16e8cd.js:6036:409
    at Pr (https://discord.com/assets/3217b04777dfcd16e8cd.js:6036:506)
    at Mr (https://discord.com/assets/3217b04777dfcd16e8cd.js:6036:920)
    at https://discord.com/assets/3217b04777dfcd16e8cd.js:6042:680
    at ke (https://discord.com/assets/3217b04777dfcd16e8cd.js:6124:404)
    at https://discord.com/assets/3217b04777dfcd16e8cd.js:6038:395
    at Vr (https://discord.com/assets/3217b04777dfcd16e8cd.js:6038:425)
    at rn (https://discord.com/assets/3217b04777dfcd16e8cd.js:6025:757)
    at nn (https://discord.com/assets/3217b04777dfcd16e8cd.js:6025:7)
    at t.unstable_runWithPriority (https://discord.com/assets/3217b04777dfcd16e8cd.js:6236:828)
    at Ki (https://discord.com/assets/3217b04777dfcd16e8cd.js:6047:117)
    at Ue (https://discord.com/assets/3217b04777dfcd16e8cd.js:6124:144)
    at en (https://discord.com/assets/3217b04777dfcd16e8cd.js:6024:800)
    at HTMLDivElement.r (https://discord.com/assets/319d4df09d3a2e7bb890.js:126:559)`

**Comment by Tyeia** [comment]
Downloaded newest version from plugin repo and it fixed itself
