### ISSUE TITLE
Invisible Typing could not be compiled

### ISSUE THREAD

**Issue by Nerodacles** [Strencher/BetterDiscordStuff#288]
`TypeError: Cannot read property 'register' of undefined
    at new e (https://discord.com/assets/d5cbd5f8612f13300561.js:4394:24)
    at new SettingsManager (betterdiscord://plugins/InvisibleTyping.plugin.js:418:6)
    at eval (betterdiscord://plugins/InvisibleTyping.plugin.js:433:21)
    at eval (betterdiscord://plugins/InvisibleTyping.plugin.js:686:5)
    at buildPlugin (betterdiscord://plugins/InvisibleTyping.plugin.js:688:4)
    at eval (betterdiscord://plugins/InvisibleTyping.plugin.js:693:2)
    at Object.requireAddon (<anonymous>:4:43095)
    at Object.loadAddon (<anonymous>:4:8859)
    at Object.loadAddon (<anonymous>:4:40847)
    at Object.loadAllAddons (<anonymous>:4:11269)
    at Object.initialize (<anonymous>:4:5963)
    at Object.initialize (<anonymous>:4:40050)
    at Object.startup (<anonymous>:4:374950)`

**Comment by HypedDomi** [comment]
Use the latest Version from GitHub
