### ISSUE TITLE
Show All Activities could not be compiled

### ISSUE THREAD

**Issue by Nerodacles** [Strencher/BetterDiscordStuff#289]
`TypeError: Cannot read property 'register' of undefined
    at new e (https://discord.com/assets/d5cbd5f8612f13300561.js:4394:24)
    at new SettingsManager (betterdiscord://plugins/ShowAllActivities.plugin.js:364:7)
    at Object.766 (betterdiscord://plugins/ShowAllActivities.plugin.js:379:22)
    at __webpack_require__ (betterdiscord://plugins/ShowAllActivities.plugin.js:597:33)
    at eval (betterdiscord://plugins/ShowAllActivities.plugin.js:631:29)
    at buildPlugin (betterdiscord://plugins/ShowAllActivities.plugin.js:633:4)
    at eval (betterdiscord://plugins/ShowAllActivities.plugin.js:638:2)
    at Object.requireAddon (<anonymous>:4:43095)
    at Object.loadAddon (<anonymous>:4:8859)
    at Object.loadAddon (<anonymous>:4:40847)
    at Object.loadAllAddons (<anonymous>:4:11269)
    at Object.initialize (<anonymous>:4:5963)
    at Object.initialize (<anonymous>:4:40050)
    at Object.startup (<anonymous>:4:374950)`

**Comment by HypedDomi** [comment]
Use the latest Version from GitHub

**Comment by FQQD** [comment]
Using the newest version from Github doesnt work.

Error:

`TypeError: Cannot read property 'default' of undefined
    at eval (betterdiscord://plugins/ShowAllActivities.plugin.js:261:124)
    at ___createMemoize___ (betterdiscord://plugins/ShowAllActivities.plugin.js:106:12)
    at Object.get @discord/flux [as @discord/flux] (betterdiscord://plugins/ShowAllActivities.plugin.js:261:12)
    at eval (betterdiscord://plugins/ShowAllActivities.plugin.js:418:40)
    at eval (betterdiscord://plugins/ShowAllActivities.plugin.js:587:5)
    at buildPlugin (betterdiscord://plugins/ShowAllActivities.plugin.js:589:4)
    at eval (betterdiscord://plugins/ShowAllActivities.plugin.js:594:2)
    at Object.requireAddon (<anonymous>:4:39192)
    at Object.loadAddon (<anonymous>:4:9163)
    at Object.loadAddon (<anonymous>:4:36864)
    at Object.loadAllAddons (<anonymous>:4:11637)
    at Object.initialize (<anonymous>:4:6059)
    at Object.initialize (<anonymous>:4:36059)
    at Object.startup (<anonymous>:4:396505)`
