### ISSUE TITLE
User Details could not be compiled

### ISSUE THREAD

**Issue by Nerodacles** [Strencher/BetterDiscordStuff#290]
`TypeError: Cannot read property 'register' of undefined
    at new e (https://discord.com/assets/d5cbd5f8612f13300561.js:4394:24)
    at new SettingsManager (betterdiscord://plugins/UserDetails.plugin.js:715:6)
    at eval (betterdiscord://plugins/UserDetails.plugin.js:729:21)
    at eval (betterdiscord://plugins/UserDetails.plugin.js:2827:5)
    at buildPlugin (betterdiscord://plugins/UserDetails.plugin.js:2829:4)
    at eval (betterdiscord://plugins/UserDetails.plugin.js:2834:2)
    at Object.requireAddon (<anonymous>:4:43095)
    at Object.loadAddon (<anonymous>:4:8859)
    at Object.loadAddon (<anonymous>:4:40847)
    at Object.loadAllAddons (<anonymous>:4:11269)
    at Object.initialize (<anonymous>:4:5963)
    at Object.initialize (<anonymous>:4:40050)
    at Object.startup (<anonymous>:4:374950)`

**Comment by Nerodacles** [comment]
2.9.0

**Comment by maenDisease** [comment]
Redownload it from GitHub or BD site, latest version is 2.9.1
