### ISSUE TITLE
Plugins broken due the recent switch to SWC (New transpiler)

### ISSUE THREAD

**Issue by ribbanya** [Strencher/BetterDiscordStuff#296]
Related to https://github.com/BetterDiscord/BetterDiscord/issues/1404.

```js
TypeError: Cannot read property 'default' of undefined
    at eval (betterdiscord://plugins/InvisibleTyping.plugin.js:248:124)
    at ___createMemoize___ (betterdiscord://plugins/InvisibleTyping.plugin.js:93:12)
    at Object.get @discord/flux [as @discord/flux] (betterdiscord://plugins/InvisibleTyping.plugin.js:248:12)
    at eval (betterdiscord://plugins/InvisibleTyping.plugin.js:404:40)
    at eval (betterdiscord://plugins/InvisibleTyping.plugin.js:653:5)
    at buildPlugin (betterdiscord://plugins/InvisibleTyping.plugin.js:655:4)
    at eval (betterdiscord://plugins/InvisibleTyping.plugin.js:660:2)
    at Object.requireAddon (<anonymous>:4:43438)
    at Object.loadAddon (<anonymous>:4:9197)
    at Object.loadAddon (<anonymous>:4:41165)
    at Object.loadAllAddons (<anonymous>:4:11607)
    at Object.initialize (<anonymous>:4:6257)
    at Object.initialize (<anonymous>:4:40368)
    at Object.startup (<anonymous>:4:376262)
```

**Comment by NotDreppy** [comment]
All plugins are broken. Good job Canary Development Team

**Comment by GodxPP** [comment]
> All plugins are broken. Good job Canary Development Team

Lmfao stfu, It's Discord that fixed a few things.

**Comment by GodxPP** [comment]
It's not their fault

**Comment by HypedDomi** [comment]
Discord switched to a new Transpiler, which is more optimized. They didn't try to kill Client mods with this change

**Comment by WhiteNervosa** [comment]
Here's an extremely jank but working version where it is enabled everywhere for people who like the QoL: https://gist.github.com/WhiteNervosa/e3853cbbe1605efbf3b6ff55b49f2ddb

**Comment by ribbanya** [comment]
> Here's an extremely jank but working version where it is enabled everywhere for people who like the QoL: https://gist.github.com/WhiteNervosa/e3853cbbe1605efbf3b6ff55b49f2ddb

Diff: https://github.com/Strencher/BetterDiscordStuff/compare/master...ribbanya:fix

**Comment by HypedDomi** [comment]
> Here's an extremely jank but working version where it is enabled everywhere for people who like the QoL: https://gist.github.com/WhiteNervosa/e3853cbbe1605efbf3b6ff55b49f2ddb

That uses old Modules. A better way is to change the config (`InvisibleTyping.config.json` file in the Plugins folder) to this:
```
{
    "currentVersionInfo": {
        "version": "1.2.2",
        "hasShownChangelog": true
    },
    "settings": {
        "autoEnable": false
    }
}
```

**Comment by NEVARLeVrai** [comment]
same with https://github.com/Strencher/BetterDiscordStuff/tree/master/ShowAllActivities

**Comment by dannydandelions** [comment]
Has invisible typing been fixed?

**Comment by HypedDomi** [comment]
Yes. Join Strenchers support server

**Comment by jukou** [comment]
> Yes. Join Strenchers support server

What's his server?

**Comment by HypedDomi** [comment]
> > Yes. Join Strenchers support server
> 
> What's his server?

https://discord.gg/gvA2ree

**Comment by etadex** [comment]
Invisible Typing still not working 
![image](https://user-images.githubusercontent.com/1521274/196118760-85b7e6cb-328c-4017-914d-046e678c2158.png)
`TypeError: Cannot read property 'default' of undefined
    at eval (betterdiscord://plugins/InvisibleTyping.plugin.js:248:124)
    at ___createMemoize___ (betterdiscord://plugins/InvisibleTyping.plugin.js:93:12)
    at Object.get @discord/flux [as @discord/flux] (betterdiscord://plugins/InvisibleTyping.plugin.js:248:12)
    at eval (betterdiscord://plugins/InvisibleTyping.plugin.js:404:40)
    at eval (betterdiscord://plugins/InvisibleTyping.plugin.js:653:5)
    at buildPlugin (betterdiscord://plugins/InvisibleTyping.plugin.js:655:4)
    at eval (betterdiscord://plugins/InvisibleTyping.plugin.js:660:2)
    at Object.requireAddon (<anonymous>:4:39280)
    at Object.loadAddon (<anonymous>:4:9251)
    at Object.loadAddon (<anonymous>:4:36952)
    at AsyncFunction.<anonymous> (<anonymous>:4:7243)`

**Comment by patjldeiM0IP** [comment]
It's now working but `autoEnable` doesn't do anything, whether set to `true` or `false` typing indicator is always enabled. There's also now no plugin settings in BD.

**Comment by ceeeej1141** [comment]
UserDetails v2.9.1 doesn't work with the newest Discord update. Has anyone found any fix yet? Thanks.

**Comment by imnew827** [comment]
fix copier?

**Comment by sponnify** [comment]
StatusEverywhere still unable to load

**Comment by HypedDomi** [comment]
Strencher didn't fixed it yet

**Comment by sponnify** [comment]
Betterbannedusers still unable to load

**Comment by othello777** [comment]
VoiceChatNotifications is broken
```js
TypeError: Cannot read property 'default' of undefined
    at eval (betterdiscord://plugins/VoiceChatNotifications.plugin.js:250:124)
    at ___createMemoize___ (betterdiscord://plugins/VoiceChatNotifications.plugin.js:95:12)
    at Object.get @discord/flux [as @discord/flux] (betterdiscord://plugins/VoiceChatNotifications.plugin.js:250:12)
    at eval (betterdiscord://plugins/VoiceChatNotifications.plugin.js:484:40)
    at eval (betterdiscord://plugins/VoiceChatNotifications.plugin.js:1108:5)
    at buildPlugin (betterdiscord://plugins/VoiceChatNotifications.plugin.js:1110:4)
    at eval (betterdiscord://plugins/VoiceChatNotifications.plugin.js:1115:2)
    at Object.requireAddon (<anonymous>:4:39192)
    at Object.loadAddon (<anonymous>:4:9163)
    at Object.loadAddon (<anonymous>:4:36864)
    at AsyncFunction.<anonymous> (<anonymous>:4:7155)
    ```

**Comment by othello777** [comment]
by @eden333
> [ShowAllActivities] Can’t compile
> 
> ![image](https://user-images.githubusercontent.com/18154402/200847674-04683245-9299-4d58-b044-30164b456254.png)

**Comment by HypedDomi** [comment]
I created a [list with known broken plugins](https://github.com/Strencher/BetterDiscordStuff/issues/324). Please ping me when you found a plugin which isn't in this list.
