### ISSUE TITLE
UserDetails v2.9.1 broken with new discord update

### ISSUE THREAD

**Issue by mysticentity** [Strencher/BetterDiscordStuff#299]
Describe the bug

Plugin failing to compile.

To reproduce

    Have plugin in folder, reload discord
    see plugin fail to compile

OS version

Windows 10 Home 64 bit, version: 20H2, OS Build: 19042.1526, Experience: Windows Feature Experience Pack 120.2212.4170.0

Discord version
Stable 150347 (4e21937)

BetterDiscord version
(Cannot currently see)

Plugin version
v2.9.1

Additional context:
Log when error occurred:

`TypeError: Cannot read property 'default' of undefined
    at eval (betterdiscord://plugins/UserDetails.plugin.js:255:124)
    at ___createMemoize___ (betterdiscord://plugins/UserDetails.plugin.js:100:12)
    at Object.get @discord/flux [as @discord/flux] (betterdiscord://plugins/UserDetails.plugin.js:255:12)
    at eval (betterdiscord://plugins/UserDetails.plugin.js:604:40)
    at eval (betterdiscord://plugins/UserDetails.plugin.js:2535:5)
    at buildPlugin (betterdiscord://plugins/UserDetails.plugin.js:2537:4)
    at eval (betterdiscord://plugins/UserDetails.plugin.js:2542:2)
    at Object.requireAddon (<anonymous>:4:43438)
    at Object.loadAddon (<anonymous>:4:9197)
    at Object.loadAddon (<anonymous>:4:41165)
    at AsyncFunction.<anonymous> (<anonymous>:4:7353)`

**Comment by HypedDomi** [comment]
Known. Use the pinned issue
