### ISSUE TITLE
addon cannot be compiled

### ISSUE THREAD

**Issue by moosje2003** [Strencher/BetterDiscordStuff#305]
i get the error cannot be compiled 

TypeError: Cannot read property 'default' of undefined
    at eval (betterdiscord://plugins/InvisibleTyping.plugin.js:248:124)
    at ___createMemoize___ (betterdiscord://plugins/InvisibleTyping.plugin.js:93:12)
    at Object.get @discord/flux [as @discord/flux] (betterdiscord://plugins/InvisibleTyping.plugin.js:248:12)
    at eval (betterdiscord://plugins/InvisibleTyping.plugin.js:404:40)
    at eval (betterdiscord://plugins/InvisibleTyping.plugin.js:653:5)
    at buildPlugin (betterdiscord://plugins/InvisibleTyping.plugin.js:655:4)
    at eval (betterdiscord://plugins/InvisibleTyping.plugin.js:660:2)
    at Object.requireAddon (<anonymous>:4:43438)
    at Object.loadAddon (<anonymous>:4:9197)
    at Object.loadAddon (<anonymous>:4:41165)
    at Object.reloadAddon (<anonymous>:4:10047)
    at AsyncFunction.<anonymous> (<anonymous>:4:7387)

**Comment by HypedDomi** [comment]
Known. Please use the pinned issue
