### ISSUE TITLE
it always says that an error was emcountered why loading

### ISSUE THREAD

**Issue by xItzShiro** [Strencher/BetterDiscordStuff#306]

**Comment by xItzShiro** [comment]
TypeError: Cannot read property 'default' of undefined
    at eval (betterdiscord://plugins/ShowAllActivities.plugin.js:261:124)
    at ___createMemoize___ (betterdiscord://plugins/ShowAllActivities.plugin.js:106:12)
    at Object.get @discord/flux [as @discord/flux] (betterdiscord://plugins/ShowAllActivities.plugin.js:261:12)
    at eval (betterdiscord://plugins/ShowAllActivities.plugin.js:418:40)
    at eval (betterdiscord://plugins/ShowAllActivities.plugin.js:587:5)
    at buildPlugin (betterdiscord://plugins/ShowAllActivities.plugin.js:589:4)
    at eval (betterdiscord://plugins/ShowAllActivities.plugin.js:594:2)
    at Object.requireAddon (<anonymous>:4:39739)
    at Object.loadAddon (<anonymous>:4:9809)
    at Object.loadAddon (<anonymous>:4:37466)
    at Object.reloadAddon (<anonymous>:4:10655)
    at AsyncFunction.<anonymous> (<anonymous>:4:7835)

**Comment by fowlis** [comment]
The plugin is broken. See the pinned issue https://github.com/Strencher/BetterDiscordStuff/issues/296
