### ISSUE TITLE
VoiceChatNotifications is broken

### ISSUE THREAD

**Issue by othello777** [Strencher/BetterDiscordStuff#316]
```js
TypeError: Cannot read property 'default' of undefined
    at eval (betterdiscord://plugins/VoiceChatNotifications.plugin.js:250:124)
    at ___createMemoize___ (betterdiscord://plugins/VoiceChatNotifications.plugin.js:95:12)
    at Object.get @discord/flux [as @discord/flux] (betterdiscord://plugins/VoiceChatNotifications.plugin.js:250:12)
    at eval (betterdiscord://plugins/VoiceChatNotifications.plugin.js:484:40)
    at eval (betterdiscord://plugins/VoiceChatNotifications.plugin.js:1108:5)
    at buildPlugin (betterdiscord://plugins/VoiceChatNotifications.plugin.js:1110:4)
    at eval (betterdiscord://plugins/VoiceChatNotifications.plugin.js:1115:2)
    at Object.requireAddon (<anonymous>:4:39192)
    at Object.loadAddon (<anonymous>:4:9163)
    at Object.loadAddon (<anonymous>:4:36864)
    at AsyncFunction.<anonymous> (<anonymous>:4:7155)
    ```

**Comment by HypedDomi** [comment]
Could you post this into #296

**Comment by othello777** [comment]
@HypedDomi sure thing
