### ISSUE TITLE
[Statu Everywhere] plugin could not be compiled

### ISSUE THREAD

**Issue by GAbO1254** [Strencher/BetterDiscordStuff#322]
When trying to load the plugin, it returns a "Could not be compiled" error:
```
TypeError: Cannot read property 'default' of undefined
    at eval (betterdiscord://plugins/StatusEverywhere.plugin.js:277:124)
    at ___createMemoize___ (betterdiscord://plugins/StatusEverywhere.plugin.js:122:12)
    at Object.get @discord/flux [as @discord/flux] (betterdiscord://plugins/StatusEverywhere.plugin.js:277:12)
    at eval (betterdiscord://plugins/StatusEverywhere.plugin.js:495:40)
    at eval (betterdiscord://plugins/StatusEverywhere.plugin.js:1588:5)
    at buildPlugin (betterdiscord://plugins/StatusEverywhere.plugin.js:1590:4)
    at eval (betterdiscord://plugins/StatusEverywhere.plugin.js:1595:2)
    at Object.requireAddon (<anonymous>:4:39192)
    at Object.loadAddon (<anonymous>:4:9163)
    at Object.loadAddon (<anonymous>:4:36864)
    at Object.reloadAddon (<anonymous>:4:10053)
    at AsyncFunction.<anonymous> (<anonymous>:4:7189)
```

**Comment by HypedDomi** [comment]
Known. Please use this issue:
- https://github.com/Strencher/BetterDiscordStuff/issues/296
