### ISSUE TITLE
broken betterbannedusers

### ISSUE THREAD

**Issue by B-Nerd** [Strencher/BetterDiscordStuff#326]
after the big better discord update this plugin is broken it could not compile so @Strencher please fix'
ypeError: Cannot read property 'default' of undefined
    at eval (betterdiscord://plugins/BetterBannedUsers.plugin.js:264:124)
    at ___createMemoize___ (betterdiscord://plugins/BetterBannedUsers.plugin.js:109:12)
    at Object.get @discord/flux [as @discord/flux] (betterdiscord://plugins/BetterBannedUsers.plugin.js:264:12)
    at eval (betterdiscord://plugins/BetterBannedUsers.plugin.js:426:40)
    at eval (betterdiscord://plugins/BetterBannedUsers.plugin.js:901:5)
    at buildPlugin (betterdiscord://plugins/BetterBannedUsers.plugin.js:903:4)
    at eval (betterdiscord://plugins/BetterBannedUsers.plugin.js:908:2)
    at Object.requireAddon (<anonymous>:4:37112)
    at Object.loadAddon (<anonymous>:4:8234)
    at Object.loadAddon (<anonymous>:4:34784)
    at Object.loadAllAddons (<anonymous>:4:10708)
    at Object.initialize (<anonymous>:4:5130)
    at Object.initialize (<anonymous>:4:33979)
    at Object.startup (<anonymous>:4:390667)

**Comment by HypedDomi** [comment]
Known. Wait for an update or check the pinned issue. I'll update it when a fix for a plugin is released
- https://github.com/Strencher/BetterDiscordStuff/issues/324
