### ISSUE TITLE
UserDetails - Compile Issue

### ISSUE THREAD

**Issue by iCry1337** [Strencher/BetterDiscordStuff#327]
```log
TypeError: Cannot read property 'default' of undefined
    at eval (betterdiscord://plugins/UserDetails.plugin.js:255:124)
    at ___createMemoize___ (betterdiscord://plugins/UserDetails.plugin.js:100:12)
    at Object.get @discord/flux [as @discord/flux] (betterdiscord://plugins/UserDetails.plugin.js:255:12)
    at eval (betterdiscord://plugins/UserDetails.plugin.js:604:40)
    at eval (betterdiscord://plugins/UserDetails.plugin.js:2564:5)
    at buildPlugin (betterdiscord://plugins/UserDetails.plugin.js:2566:4)
    at eval (betterdiscord://plugins/UserDetails.plugin.js:2571:2)
    at Object.requireAddon (<anonymous>:4:37112)
    at Object.loadAddon (<anonymous>:4:8234)
    at Object.loadAddon (<anonymous>:4:34784)
    at Object.reloadAddon (<anonymous>:4:9124)
    at AsyncFunction.<anonymous> (<anonymous>:4:6260)
```

There has something changed in here?

**Comment by fowlis** [comment]
Known, see #324
