### ISSUE TITLE
[StatusEverywhere] Could not be compiled error / An error was encountered while trying to load this plugin.

### ISSUE THREAD

**Issue by foursplaysroblox** [Strencher/BetterDiscordStuff#341]
Version: v2.3.5
Error Log:
TypeError: Cannot read properties of undefined (reading 'default')
    at eval (betterdiscord://plugins/StatusEverywhere.plugin.js:277:124)
    at ___createMemoize___ (betterdiscord://plugins/StatusEverywhere.plugin.js:122:12)
    at get @discord/flux [as @discord/flux] (betterdiscord://plugins/StatusEverywhere.plugin.js:277:12)
    at eval (betterdiscord://plugins/StatusEverywhere.plugin.js:495:40)
    at eval (betterdiscord://plugins/StatusEverywhere.plugin.js:1588:5)
    at buildPlugin (betterdiscord://plugins/StatusEverywhere.plugin.js:1590:4)
    at eval (betterdiscord://plugins/StatusEverywhere.plugin.js:1595:2)
    at x.requireAddon (<anonymous>:4:37871)
    at x.loadAddon (<anonymous>:4:8814)
    at x.loadAddon (<anonymous>:4:35543)
    at AsyncFunction.<anonymous> (<anonymous>:4:6806)

**Comment by HypedDomi** [comment]
Known: 
- https://github.com/Strencher/BetterDiscordStuff/issues/324
