### ISSUE TITLE
[ChannelDms] Plugin could not be compiled.

### ISSUE THREAD

**Issue by WolfCoolCamelCase** [Strencher/BetterDiscordStuff#344]
I'm trying to use ChannelDms plugin but when I add it it says that plugin could not be compiled. Here're logs:

TypeError: Cannot read properties of undefined (reading 'reduce')
    at eval (betterdiscord://plugins/ChannelDms.plugin.js:261:143)
    at \_\_\_createMemoize___ (betterdiscord://plugins/ChannelDms.plugin.js:94:12)
    at get @discord/icons [as @discord/icons] (betterdiscord://plugins/ChannelDms.plugin.js:261:12)
    at eval (betterdiscord://plugins/ChannelDms.plugin.js:423:41)
    at eval (betterdiscord://plugins/ChannelDms.plugin.js:950:5)
    at buildPlugin (betterdiscord://plugins/ChannelDms.plugin.js:952:4)
    at eval (betterdiscord://plugins/ChannelDms.plugin.js:957:2)
    at A.requireAddon (betterdiscord/renderer.js:4:35265)
    at A.loadAddon (betterdiscord/renderer.js:4:7766)
    at A.loadAddon (betterdiscord/renderer.js:4:32937)
    at AsyncFunction.<anonymous> (betterdiscord/renderer.js:4:5758)

**Comment by HypedDomi** [comment]
- https://github.com/Strencher/BetterDiscordStuff/issues/324
