### ISSUE TITLE
usersDetails Error

### ISSUE THREAD

**Issue by jin1010101-fg** [Strencher/BetterDiscordStuff#348]
TypeError: Cannot read properties of undefined (reading 'default')
    at eval (betterdiscord://plugins/UserDetails.plugin.js:255:124)
    at ___createMemoize___ (betterdiscord://plugins/UserDetails.plugin.js:100:12)
    at get @discord/flux [as @discord/flux] (betterdiscord://plugins/UserDetails.plugin.js:255:12)
    at eval (betterdiscord://plugins/UserDetails.plugin.js:604:40)
    at eval (betterdiscord://plugins/UserDetails.plugin.js:2564:5)
    at buildPlugin (betterdiscord://plugins/UserDetails.plugin.js:2566:4)
    at eval (betterdiscord://plugins/UserDetails.plugin.js:2571:2)
    at A.requireAddon (betterdiscord/renderer.js:4:35124)
    at A.loadAddon (betterdiscord/renderer.js:4:7625)
    at A.loadAddon (betterdiscord/renderer.js:4:32796)
    at AsyncFunction.<anonymous> (betterdiscord/renderer.js:4:5617)
    
    what is this error

**Comment by HypedDomi** [comment]
The plugin is broken. Strencher need to fix it

**Comment by jin1010101-fg** [comment]
omg,When will it be fixed

**Comment by HypedDomi** [comment]
No clue. Theres no ETA for it

**Comment by jin1010101-fg** [comment]
Oh no...

**Comment by HypedDomi** [comment]
For more Info, see: https://github.com/Strencher/BetterDiscordStuff/issues/324
