### ISSUE TITLE
[Bug] Status Everywhere

### ISSUE THREAD

**Issue by yarross** [Strencher/BetterDiscordStuff#355]
TypeError: Cannot read properties of undefined (reading 'default')
    at eval (betterdiscord://plugins/StatusEverywhere.plugin.js:277:124)
    at ___createMemoize___ (betterdiscord://plugins/StatusEverywhere.plugin.js:122:12)
    at get @discord/flux [as @discord/flux] (betterdiscord://plugins/StatusEverywhere.plugin.js:277:12)
    at eval (betterdiscord://plugins/StatusEverywhere.plugin.js:495:40)
    at eval (betterdiscord://plugins/StatusEverywhere.plugin.js:1588:5)
    at buildPlugin (betterdiscord://plugins/StatusEverywhere.plugin.js:1590:4)
    at eval (betterdiscord://plugins/StatusEverywhere.plugin.js:1595:2)
    at M.requireAddon (betterdiscord/renderer.js:4:35818)
    at M.loadAddon (betterdiscord/renderer.js:4:8323)
    at M.loadAddon (betterdiscord/renderer.js:4:33490)
    at AsyncFunction.<anonymous> (betterdiscord/renderer.js:4:6315)

**Comment by HypedDomi** [comment]
Known. Read #324 for more info
