### ISSUE TITLE
UserDetails  could not be compiled

### ISSUE THREAD

**Issue by maooni5** [Strencher/BetterDiscordStuff#361]
so whenever i try downloading it it says this issue and shows me this:

TypeError: Cannot read properties of undefined (reading 'default')
    at eval (betterdiscord://plugins/UserDetails.plugin.js:255:124)
    at ___createMemoize___ (betterdiscord://plugins/UserDetails.plugin.js:100:12)
    at get @discord/flux [as @discord/flux] (betterdiscord://plugins/UserDetails.plugin.js:255:12)
    at eval (betterdiscord://plugins/UserDetails.plugin.js:604:40)
    at eval (betterdiscord://plugins/UserDetails.plugin.js:2564:5)
    at buildPlugin (betterdiscord://plugins/UserDetails.plugin.js:2566:4)
    at eval (betterdiscord://plugins/UserDetails.plugin.js:2571:2)
    at M.requireAddon (betterdiscord/renderer.js:4:35818)
    at M.loadAddon (betterdiscord/renderer.js:4:8323)
    at M.loadAddon (betterdiscord/renderer.js:4:33490)
    at M.reloadAddon (betterdiscord/renderer.js:4:9211)
    at AsyncFunction.<anonymous> (betterdiscord/renderer.js:4:6349)

**Comment by HypedDomi** [comment]
https://github.com/Strencher/BetterDiscordStuff/issues/324
