### ISSUE TITLE
Fails to compile

### ISSUE THREAD

**Issue by AskAlice** [Strencher/BetterDiscordStuff#366]
```
TypeError: Cannot read properties of undefined (reading 'reduce')
    at eval (betterdiscord://plugins/ChannelDms.plugin.js:261:143)
    at ___createMemoize___ (betterdiscord://plugins/ChannelDms.plugin.js:94:12)
    at get @discord/icons [as @discord/icons] (betterdiscord://plugins/ChannelDms.plugin.js:261:12)
    at eval (betterdiscord://plugins/ChannelDms.plugin.js:423:41)
    at eval (betterdiscord://plugins/ChannelDms.plugin.js:950:5)
    at buildPlugin (betterdiscord://plugins/ChannelDms.plugin.js:952:4)
    at eval (betterdiscord://plugins/ChannelDms.plugin.js:957:2)
    at M.requireAddon (betterdiscord/renderer.js:4:35818)
    at M.loadAddon (betterdiscord/renderer.js:4:8323)
    at M.loadAddon (betterdiscord/renderer.js:4:33490)
    at AsyncFunction.<anonymous> (betterdiscord/renderer.js:4:6315)
 ```
 
 looks like some issue with the BD api changing. the reduce is called on [this line](https://github.com/Strencher/BetterDiscordStuff/blob/93608e8d64458465845e1ee0586d700961ced816/ChannelDms/ChannelDms.plugin.js#L259)
 ```js
 BdApi.findAllModules(m => m.displayName && ~m.toString().indexOf('currentColor')).reduce((icons, icon) => (icons[icon.displayName] = icon, icons), {}))
 ```

**Comment by HypedDomi** [comment]
https://github.com/Strencher/BetterDiscordStuff/issues/324
