### ISSUE TITLE
[CRASH - PlatformIndicators] Could not fire before callback of default (BetterDiscord Patcher)

### ISSUE THREAD

**Issue by Riddim-GLiTCH** [Strencher/BetterDiscordStuff#379]
Currently, Discord semi-crashes with the plugin enabled. Taking you to the "Well This is Awkward" screen.
An error log can be found below
```log
[BetterDiscord] [Patcher] Could not fire before callback of default for APlatformIndicators TypeError: Cannot read properties of undefined (reading 'decorations')
    at Object.eval [as callback] (APlatformIndicators.plugin.js:609:38)
    at renderer.js:5766:22
    at J (65573.3d56d56002765d7a9da8.js:1:742720)
    at 65573.3d56d56002765d7a9da8.js:1:805598
    at o7 (65573.3d56d56002765d7a9da8.js:1:805695)
    at sC (65573.3d56d56002765d7a9da8.js:1:834363)
    at sI (65573.3d56d56002765d7a9da8.js:1:835165)
    at sT (65573.3d56d56002765d7a9da8.js:1:831898)
    at sD (65573.3d56d56002765d7a9da8.js:1:830453)
    at L (65573.3d56d56002765d7a9da8.js:1:901278)
    at O (65573.3d56d56002765d7a9da8.js:1:901808)
    at L.<computed> (65573.3d56d56002765d7a9da8.js:1:98850)
    at T (65573.3d56d56002765d7a9da8.js:1:98603)
    at MessagePort.Y (65573.3d56d56002765d7a9da8.js:1:98662)
```

Other important information includes:
Discord build: Canary 252812 (dc56b15)
Host: 1.0.846 x64 (40727)
OpenAsar: Nightly (1c24e09)
OS: Windows 10 64-Bit (10.0.22621)

*It should be noted that multiple people are reporting this error across different systems and discord branches.

anything else: This screenshot from a more expansive error log, provided by Sarah
![image](https://github.com/Strencher/BetterDiscordStuff/assets/87764384/5de9def3-6c9c-4c1c-a318-d346eb80bfa9)

**Comment by Knewest** [comment]
The BetterDiscord support thread discussing this can be found through this link: [https://ptb.discord.com/channels/86004744966914048/1182793881004277842](https://ptb.discord.com/channels/86004744966914048/1182793881004277842)

**Comment by pinetreemoonlight** [comment]
Same on Discord and Discord PTB clients
