### ISSUE TITLE
UserDetails v2.9.1 not being loaded by BD

### ISSUE THREAD

**Issue by UX0l0l** [Strencher/BetterDiscordStuff#389]
When I install the plugin UserDetails, I'm given this error from BD, alongside a message saying it can't load/compile it:

`TypeError: Cannot read properties of undefined (reading 'BUILT_IN_SECTIONS')
    at eval (betterdiscord://plugins/UserDetails.plugin.js:640:25)
    at eval (betterdiscord://plugins/UserDetails.plugin.js:2564:5)
    at buildPlugin (betterdiscord://plugins/UserDetails.plugin.js:2566:4)
    at eval (betterdiscord://plugins/UserDetails.plugin.js:2571:2)
    at A.requireAddon (betterdiscord/renderer.js:5:33832)
    at A.loadAddon (betterdiscord/renderer.js:5:6386)
    at A.loadAddon (betterdiscord/renderer.js:5:31500)
    at AsyncFunction.<anonymous> (betterdiscord/renderer.js:5:4366)`

Any help at resolving the issue would be appreciated.

**Comment by domi-btnr** [comment]
Known. Read #324
