### ISSUE TITLE
[StatusEverywhere] Plugin could not be Compiled - Plugin unusable

### ISSUE THREAD

**Issue by Riddim-GLiTCH** [Strencher/BetterDiscordStuff#391]
Curretnly, the plugin fails to compile when betterdiscord starts.
I was able to record the following log:
```log
TypeError: Cannot read properties of undefined (reading 'reduce')
    at eval (betterdiscord://plugins/StatusEverywhere.plugin.js:289:143)
    at ___createMemoize___ (betterdiscord://plugins/StatusEverywhere.plugin.js:122:12)
    at get @discord/icons [as @discord/icons] (betterdiscord://plugins/StatusEverywhere.plugin.js:289:12)
    at eval (betterdiscord://plugins/StatusEverywhere.plugin.js:500:41)
    at eval (betterdiscord://plugins/StatusEverywhere.plugin.js:1588:5)
    at buildPlugin (betterdiscord://plugins/StatusEverywhere.plugin.js:1590:4)
    at eval (betterdiscord://plugins/StatusEverywhere.plugin.js:1595:2)
    at A.requireAddon (betterdiscord/renderer.js:5:33832)
    at A.loadAddon (betterdiscord/renderer.js:5:6386)
    at A.loadAddon (betterdiscord/renderer.js:5:31500)
    at A.loadAllAddons (betterdiscord/renderer.js:5:8878)
    at A.initialize (betterdiscord/renderer.js:5:3258)
    at A.initialize (betterdiscord/renderer.js:5:30699)
    at Object.startup (betterdiscord/renderer.js:5:369099)
```
Other information:
Discord Version: Stable 263582 (53bdc39)
Host: 0.0.42 x64 (Linux 64-Bit) 
BetterDiscord version: Github Release (V1.9.7)
Linux Kernel Version: 6.7.2-Zen1-1-Zen 

The latter bit of information should not matter too much, as I looked into this issue from someone who I assume is on windows. See [this thread](https://canary.discord.com/channels/86004744966914048/1203477873185390715) in the BetterDiscord Support Server.

**Comment by domi-btnr** [comment]
The plugin is known to be broken (https://github.com/Strencher/BetterDiscordStuff/issues/324). I'll close this issue to not have duplicates of already reported issues

**Comment by eSSy-90** [comment]
When I launch discord, it shows this:
```
TypeError: Class extends value undefined is not a constructor or null
    at eval (betterdiscord://plugins/UnreadCountBadges.plugin.js:474:55)
    at eval (betterdiscord://plugins/UnreadCountBadges.plugin.js:1241:5)
    at buildPlugin (betterdiscord://plugins/UnreadCountBadges.plugin.js:1243:4)
    at eval (betterdiscord://plugins/UnreadCountBadges.plugin.js:1248:2)
    at N.requireAddon (betterdiscord/renderer.js:5:28792)
    at N.loadAddon (betterdiscord/renderer.js:5:6412)
    at N.loadAddon (betterdiscord/renderer.js:5:26460)
    at N.loadAllAddons (betterdiscord/renderer.js:5:9469)
    at N.initialize (betterdiscord/renderer.js:5:3284)
    at N.initialize (betterdiscord/renderer.js:5:25573)
    at Object.startup (betterdiscord/renderer.js:5:408848)
```

**Comment by domi-btnr** [comment]
> When I launch discord, it shows this:
> 
> ```
> TypeError: Class extends value undefined is not a constructor or null
>     at eval (betterdiscord://plugins/UnreadCountBadges.plugin.js:474:55)
>     at eval (betterdiscord://plugins/UnreadCountBadges.plugin.js:1241:5)
>     at buildPlugin (betterdiscord://plugins/UnreadCountBadges.plugin.js:1243:4)
>     at eval (betterdiscord://plugins/UnreadCountBadges.plugin.js:1248:2)
>     at N.requireAddon (betterdiscord/renderer.js:5:28792)
>     at N.loadAddon (betterdiscord/renderer.js:5:6412)
>     at N.loadAddon (betterdiscord/renderer.js:5:26460)
>     at N.loadAllAddons (betterdiscord/renderer.js:5:9469)
>     at N.initialize (betterdiscord/renderer.js:5:3284)
>     at N.initialize (betterdiscord/renderer.js:5:25573)
>     at Object.startup (betterdiscord/renderer.js:5:408848)
> ```

Please read the pinned issue
