### ISSUE TITLE
APlatformIndicators now broken

### ISSUE THREAD

**Issue by movieslol** [Strencher/BetterDiscordStuff#394]
Loading the plugin now results in this error:
![image](https://github.com/Strencher/BetterDiscordStuff/assets/144293482/c2d0cd4e-6e6d-47a9-adb4-41125cdad744)

**Comment by Azukiov** [comment]
for me too

```md
## Discord Info
stable 277953 (2ff410b) Host 1.0.9037 x86 (45369) Windows 10 64-bit (10.0.19045)

## BetterDiscord
stable 1.10.1

### Plugins (12 Enabled):
- BDFDB (Enabled)
- ZeresPluginLibrary (Enabled)
- XenoLib (Enabled)
- APlatformIndicators
- Channel Permissions (Enabled)
- CustomStatusPresets (Enabled)
- DoNotTrack (Enabled)
- Hide Channels (Enabled)
- InvisibleTyping (Enabled)
- MessageLoggerV2 (Enabled)
- NoSpotifyPause (Enabled)
- PermissionsViewer (Enabled)
- PlatformEmulator
- SplitLargeMessages (Enabled)

### Themes (0 Enabled):

```

TypeError: Class extends value undefined is not a constructor or null
    at eval (betterdiscord://plugins/APlatformIndicators.plugin.js:174:51)
    at N.requireAddon (betterdiscord/renderer.js:5:28792)
    at N.loadAddon (betterdiscord/renderer.js:5:6412)
    at N.loadAddon (betterdiscord/renderer.js:5:26460)
    at N.loadAllAddons (betterdiscord/renderer.js:5:9469)
    at N.initialize (betterdiscord/renderer.js:5:3284)
    at N.initialize (betterdiscord/renderer.js:5:25573)
    at Object.startup (betterdiscord/renderer.js:5:408848)

**Comment by Darkn8tT** [comment]
same
TypeError: Class extends value undefined is not a constructor or null
    at eval (betterdiscord://plugins/APlatformIndicators.plugin.js:174:51)
    at N.requireAddon (betterdiscord/renderer.js:5:28792)
    at N.loadAddon (betterdiscord/renderer.js:5:6412)
    at N.loadAddon (betterdiscord/renderer.js:5:26460)
    at N.reloadAddon (betterdiscord/renderer.js:5:7302)
    at AsyncFunction.<anonymous> (betterdiscord/renderer.js:5:4426)

**Comment by domi-btnr** [comment]
Should be fixed. Wait for the workflow to build the plugin then redownload from GitHub
