### ISSUE TITLE
APlatformIndicators Causing Crashes

### ISSUE THREAD

**Issue by movieslol** [Strencher/BetterDiscordStuff#398]
For some reason, sometimes enabling APlatformIndicators (usually along with other plugins) causes Discord to crash with no fix besides repairing BetterDiscord. Discord seems to be working fine without the plugin, and when looking at the DevTools, it mentions this plugin, which is the reason I am posting this bug report here. Help would be appreciated.

**Comment by domi-btnr** [comment]
The Repair Option just disables all plugins and reinstalls BD. But can you send the Error from the Console? That would help

**Comment by Miyxzu** [comment]
I also was getting crashes when using PlatformIndicators today and was able to isolate it down to this error (see below)

65573.93bf77f607ed3f9b1587.js:1 TypeError: Class constructor Rt cannot be invoked without 'new'
    at aS (58661.0e645890ea50d43648f6.js:12:899964)
    at u (58661.0e645890ea50d43648f6.js:12:955175)
    at sB (58661.0e645890ea50d43648f6.js:12:938190)
    at 58661.0e645890ea50d43648f6.js:12:938056
    at sF (58661.0e645890ea50d43648f6.js:12:938064)
    at sC (58661.0e645890ea50d43648f6.js:12:934815)
    at sT (58661.0e645890ea50d43648f6.js:12:933370)
    at x (58661.0e645890ea50d43648f6.js:12:1125228)
    at A (58661.0e645890ea50d43648f6.js:12:1125758)
    at D.<computed> (58661.0e645890ea50d43648f6.js:1:501525)
    at M (58661.0e645890ea50d43648f6.js:1:501290)
    at MessagePort.k (58661.0e645890ea50d43648f6.js:1:501349)
    
 I am not sure if movieslol is also has the same error but this is what I was able to find for myself

**Comment by PatrickSantoZZ** [comment]
can confirm i got the same issue as @Miyxzu it stopped working after a discord restart. i sadly didnt noticed any discord update today. did the usual remove all plugins and drop them one by one into the folder again and yeah its the Plattform Indicator.

**Comment by ColonelGerdauf** [comment]
I had singled out this plugin as the cause of a random start-crash an hour ago. It had worked until now without issue, and there wasn't an update to the plugin or to Discord itself by the time the crash happened.
