### ISSUE TITLE
PlatformIndicators crashes discord

### ISSUE THREAD

**Issue by Clyde-Timonera** [Strencher/BetterDiscordStuff#403]
As soon as you open your dms or a server it causes it to crash, crash recovery also cannot do anything and the only solution that I can find for this is to disable the plugin.
![image](https://github.com/Strencher/BetterDiscordStuff/assets/78290310/069c7e86-ae48-4d5b-94ac-b18266a8a714)

**Comment by Leah96xxx** [comment]
Having the same issue here.

Console logs the following several times at the point of crash:
```
[BetterDiscord] [Patcher] Could not fire before callback of default for APlatformIndicators TypeError: Cannot read properties of undefined (reading 'decorations')
    at Object.eval [as callback] (APlatformIndicators.plugin.js:634:42)
    at renderer.js:5:22652
    at $ (58661.0e645890ea50d43648f6.js:12:845637)
    at 58661.0e645890ea50d43648f6.js:12:908515
    at a9 (58661.0e645890ea50d43648f6.js:12:908612)
    at sI (58661.0e645890ea50d43648f6.js:12:937280)
    at sF (58661.0e645890ea50d43648f6.js:12:938082)
    at sT (58661.0e645890ea50d43648f6.js:12:933101)
    at x (58661.0e645890ea50d43648f6.js:12:1125228)
    at A (58661.0e645890ea50d43648f6.js:12:1125758)
    at D.<computed> (58661.0e645890ea50d43648f6.js:1:501525)
    at M (58661.0e645890ea50d43648f6.js:1:501290)
    at MessagePort.k (58661.0e645890ea50d43648f6.js:1:501349)
```

The following is also logged at the same time:
```
ypeError: Class constructor Rt cannot be invoked without 'new'
    at aS (58661.0e645890ea50d43648f6.js:12:899964)
    at u (58661.0e645890ea50d43648f6.js:12:955175)
    at sB (58661.0e645890ea50d43648f6.js:12:938190)
    at 58661.0e645890ea50d43648f6.js:12:938056
    at sF (58661.0e645890ea50d43648f6.js:12:938064)
    at sC (58661.0e645890ea50d43648f6.js:12:934815)
    at sT (58661.0e645890ea50d43648f6.js:12:933370)
    at x (58661.0e645890ea50d43648f6.js:12:1125228)
    at A (58661.0e645890ea50d43648f6.js:12:1125758)
    at D.<computed> (58661.0e645890ea50d43648f6.js:1:501525)
    at M (58661.0e645890ea50d43648f6.js:1:501290)
    at MessagePort.k (58661.0e645890ea50d43648f6.js:1:501349)
```

**Comment by Technetium1** [comment]
Should be fixed with https://github.com/Strencher/BetterDiscordStuff/pull/402, see https://github.com/Strencher/BetterDiscordStuff/issues/398.

**Comment by Leah96xxx** [comment]
Confirmed that's fixed it for me after manually updating

**Comment by Clyde-Timonera** [comment]
Where can I find the update? still stuck on the broken version both from github and betterdiscord

**Comment by Clyde-Timonera** [comment]
Found it, and it functions just fine now.

**Comment by Syilumi** [comment]
how do i get the fixed version?

**Comment by AcesGamingUK** [comment]
can confirm that manually updating works,
( I just copied and pasted the .js from the master branch)

thanks ❤️

**Comment by domi-btnr** [comment]
> how do i get the fixed version?

Click [APlatformIndicators.plugin.js](https://raw.githubusercontent.com/Strencher/BetterDiscordStuff/master/PlatformIndicators/APlatformIndicators.plugin.js) and download that File. Otherwise wait for the update to be approved on the BD Website
