### ISSUE TITLE
[PlatformIndicators] Failure to Compile

### ISSUE THREAD

**Issue by whataboutism-alos** [Strencher/BetterDiscordStuff#406]
An error was encountered while trying to load this plugin.
```
TypeError: Cannot read properties of undefined (reading 'Store')
    at eval (betterdiscord://plugins/APlatformIndicators.plugin.js:174:51)
    at N.requireAddon (betterdiscord/renderer.js:5:28601)
    at N.loadAddon (betterdiscord/renderer.js:5:6221)
    at N.loadAddon (betterdiscord/renderer.js:5:26269)
    at betterdiscord/renderer.js:5:4201
```

**Comment by zrodevkaan** [comment]
Yup. I know. I am getting to it.

**Comment by domi-btnr** [comment]
Fixed
