### ISSUE TITLE
Could Not Compile

### ISSUE THREAD

**Issue by NotSomeBlox** [Strencher/BetterDiscordStuff#409]
When loading, ShowAllActivities shows this as why it could not compile:
TypeError: Cannot read properties of undefined (reading 'useStateFromStores')
    at eval (betterdiscord://plugins/ShowAllActivities.plugin.js:334:76)
    at N.requireAddon (betterdiscord/renderer.js:5:28601)
    at N.loadAddon (betterdiscord/renderer.js:5:6221)
    at N.loadAddon (betterdiscord/renderer.js:5:26269)
    at betterdiscord/renderer.js:5:4201

**Comment by domi-btnr** [comment]
Please check the pinned posts
