### ISSUE TITLE
[BUG] [Invisible Typing] Discord crash when opening Audit Log.

### ISSUE THREAD

**Issue by Jugom** [Strencher/BetterDiscordStuff#412]
As the title says.
If I open the Audit log in a discord server, discord crashes. 
Console shows an error with invisible typing. 
Disabled Invisible typing and discord no longer crashes when opening the Audit Log.

**Comment by domi-btnr** [comment]
Could you paste the Error Message here?

**Comment by XxUnkn0wnxX** [comment]
well I'm not getting crashes but typing has been dead for me for a while, I believe..
getting console errors:

<img width="1266" alt="Screen Shot 2024-07-04 at 6 44 06 am" src="https://github.com/Strencher/BetterDiscordStuff/assets/2242880/e1a59eb8-1558-4640-a1d6-d53e7b734251">

<details><summary>Log</summary>

```
tx @ web.3e849ca97f18986397a1.js:12
web.3e849ca97f18986397a1.js:12 Failed to request permissions: TypeError: Cannot read properties of undefined (reading 'can')
    at InvisibleTypingButton.canViewChannel (InvisibleTyping.plugin.js:106:58)
    at InvisibleTypingButton.shouldShow (InvisibleTyping.plugin.js:121:23)
    at Object.eval [as callback] (InvisibleTyping.plugin.js:510:40)
    at renderer.js:5:22972
    at aA (web.3e849ca97f18986397a1.js:12:990088)
    at oh (web.3e849ca97f18986397a1.js:12:1001987)
    at o_ (web.3e849ca97f18986397a1.js:12:1001193)
    at od (web.3e849ca97f18986397a1.js:12:1000793)
    at l (web.3e849ca97f18986397a1.js:12:1048685)
    at sk (web.3e849ca97f18986397a1.js:12:1028319)
    at web.3e849ca97f18986397a1.js:12:1028185
    at sG (web.3e849ca97f18986397a1.js:12:1028193)
    at sD (web.3e849ca97f18986397a1.js:12:1025278)
    at r5 (web.3e849ca97f18986397a1.js:12:973952)
    at sL (web.3e849ca97f18986397a1.js:12:1025593)
    at eU (web.3e849ca97f18986397a1.js:12:943178)
    at rs (web.3e849ca97f18986397a1.js:12:964307)
    at tk (web.3e849ca97f18986397a1.js:12:949975)
    at tx (web.3e849ca97f18986397a1.js:12:949759)
I.t.<computed> @ web.3e849ca97f18986397a1.js:12
(anonymous) @ renderer.js:5
canViewChannel @ InvisibleTyping.plugin.js:112
shouldShow @ InvisibleTyping.plugin.js:121
eval @ InvisibleTyping.plugin.js:510
(anonymous) @ renderer.js:5
aA @ web.3e849ca97f18986397a1.js:12
oh @ web.3e849ca97f18986397a1.js:12
o_ @ web.3e849ca97f18986397a1.js:12
od @ web.3e849ca97f18986397a1.js:12
l @ web.3e849ca97f18986397a1.js:12
sk @ web.3e849ca97f18986397a1.js:12
(anonymous) @ web.3e849ca97f18986397a1.js:12
```

</details>

**Comment by domi-btnr** [comment]
Fixed in https://github.com/Strencher/BetterDiscordStuff/commit/3413d0af88a3cc4c88bf374049cdc3160951164c
