### ISSUE TITLE
StatusEverywhere - Error: Could not be Compiled

### ISSUE THREAD

**Issue by niktr** [Strencher/BetterDiscordStuff#413]
![image](https://github.com/user-attachments/assets/3e355626-2cea-4146-bfb7-f9263f5f12cd)

```javascript
TypeError: Cannot read properties of undefined (reading 'default')
    at eval (betterdiscord://plugins/StatusEverywhere.plugin.js:277:124)
    at ___createMemoize___ (betterdiscord://plugins/StatusEverywhere.plugin.js:122:12)
    at get @discord/flux (betterdiscord://plugins/StatusEverywhere.plugin.js:277:12)
    at eval (betterdiscord://plugins/StatusEverywhere.plugin.js:495:40)
    at eval (betterdiscord://plugins/StatusEverywhere.plugin.js:1588:5)
    at buildPlugin (betterdiscord://plugins/StatusEverywhere.plugin.js:1590:4)
    at eval (betterdiscord://plugins/StatusEverywhere.plugin.js:1595:2)
    at N.requireAddon (betterdiscord/renderer.js:5:28601)
    at N.loadAddon (betterdiscord/renderer.js:5:6221)
    at N.loadAddon (betterdiscord/renderer.js:5:26269)
    at betterdiscord/renderer.js:5:4201
```

**Comment by Riddim-GLiTCH** [comment]
the last commit to this plugin was 2 years ago. The plugin is positively abandoned and will likely not be fixed anymore.

**Comment by domi-btnr** [comment]
#324
