### ISSUE TITLE
[Bug] Channels DM cannot load at start. Compilation issue. 

### ISSUE THREAD

**Issue by shawny43** [Strencher/BetterDiscordStuff#414]
Javascript logs:
TypeError: Cannot read properties of undefined (reading 'reduce')
    at eval (betterdiscord://plugins/ChannelDms.plugin.js:261:143)
    at ___createMemoize___ (betterdiscord://plugins/ChannelDms.plugin.js:94:12)
    at get @discord/icons (betterdiscord://plugins/ChannelDms.plugin.js:261:12)
    at eval (betterdiscord://plugins/ChannelDms.plugin.js:423:41)
    at eval (betterdiscord://plugins/ChannelDms.plugin.js:950:5)
    at buildPlugin (betterdiscord://plugins/ChannelDms.plugin.js:952:4)
    at eval (betterdiscord://plugins/ChannelDms.plugin.js:957:2)
    at N.requireAddon (betterdiscord/renderer.js:5:28601)
    at N.loadAddon (betterdiscord/renderer.js:5:6221)
    at N.loadAddon (betterdiscord/renderer.js:5:26269)
    at betterdiscord/renderer.js:5:4201

**Comment by domi-btnr** [comment]
#324
