### ISSUE TITLE
showallactivites error compiling

### ISSUE THREAD

**Issue by Kenyiro34** [Strencher/BetterDiscordStuff#415]
TypeError: Cannot read properties of undefined (reading 'useStateFromStores')
    at eval (betterdiscord://plugins/ShowAllActivities.plugin.js:334:76)
    at N.requireAddon (betterdiscord/renderer.js:5:28601)
    at N.loadAddon (betterdiscord/renderer.js:5:6221)
    at N.loadAddon (betterdiscord/renderer.js:5:26269)
    at N.reloadAddon (betterdiscord/renderer.js:5:7111)
    at betterdiscord/renderer.js:5:4235

**Comment by Riddim-GLiTCH** [comment]
https://github.com/Strencher/BetterDiscordStuff/issues/324
