### ISSUE TITLE
Error when opening discord(does not work since download)

### ISSUE THREAD

**Issue by maciupikciuxd** [Strencher/BetterDiscordStuff#416]
win11 64bit

TypeError: Cannot read properties of undefined (reading 'useStateFromStores')
    at eval (betterdiscord://plugins/ShowAllActivities.plugin.js:334:76)
    at N.requireAddon (betterdiscord/renderer.js:5:28601)
    at N.loadAddon (betterdiscord/renderer.js:5:6221)
    at N.loadAddon (betterdiscord/renderer.js:5:26269)
    at N.loadAllAddons (betterdiscord/renderer.js:5:9278)
    at N.initialize (betterdiscord/renderer.js:5:3093)
    at N.initialize (betterdiscord/renderer.js:5:25382)
    at Object.startup (betterdiscord/renderer.js:5:408589)

**Comment by Riddim-GLiTCH** [comment]
See [`#324`](https://github.com/Strencher/BetterDiscordStuff/issues/324)
