### ISSUE TITLE
[Bug]: ShowAllActivities Startup Error 

### ISSUE THREAD

**Issue by BubblyBreadysi** [Strencher/BetterDiscordStuff#428]
### Plugin

ShowAllActivities v1.1.2

### **Addon Name and Version**
ShowAllActivities v1.1.2

### **Discord Version**
**Discord** Stable 353815 (a932d4a) Host 1.0.9174 x64 (56336) Build Override: N/A Windows 11 64-bit (10.0.22631)
**BetterDiscord** stable 1.11.0

### **Describe the bug**
This startup error keeps coming up. I have had this error for a while. I can't enable this plugin either. I have reinstalled the plugin multiple times, and it still comes up.

### **To Reproduce**
Starting up discord with this plugin installed

### **Additional context**
![ShowAllActivities 1](https://github.com/user-attachments/assets/f155ac2f-f4ba-4c6d-9ad6-4ecdff34c081)
![image](https://github.com/user-attachments/assets/cc8c9a19-1292-4eef-b33d-8cdd95caa74d)

### Stacktrace

```code
TypeError: Cannot read properties of undefined (reading 'useStateFromStores')
    at eval (betterdiscord://plugins/ShowAllActivities.plugin.js:334:76)
    at N.requireAddon (betterdiscord/renderer.js:5:30017)
    at N.loadAddon (betterdiscord/renderer.js:5:7628)
    at N.loadAddon (betterdiscord/renderer.js:5:27685)
    at N.loadAllAddons (betterdiscord/renderer.js:5:10685)
    at N.initialize (betterdiscord/renderer.js:5:4500)
    at N.initialize (betterdiscord/renderer.js:5:26798)
    at Object.startup (betterdiscord/renderer.js:5:416934)
```

### Confirmation

- [X] I am using the latest version of the plugin
- [X] This issue has not already been reported

**Comment by Riddim-GLiTCH** [comment]
https://github.com/Strencher/BetterDiscordStuff/issues/324
Known, and pinned. 
Eyes are useful. Use them.
