### ISSUE TITLE
UserDetails crashes when in any server on powerCord

### ISSUE THREAD

**Issue by defoNotAnAlt** [Strencher/BetterDiscordStuff#89]
I don't really have any info on this other than this error the CrachRecovery plugin gave me:
```console
[CrashRecovery] HEY OVER HERE! Show this to the plugin developer or in the support server!
Prettified stacktraces, stack:
 TypeError: Cannot read property 'status' of undefined 
Component stack:
     at P (https://canary.discord.com/assets/d94161c3f88cbee6a586.js:961:488)
    at u (https://canary.discord.com/assets/d94161c3f88cbee6a586.js:3915:679)
    at div
    at t (https://canary.discord.com/assets/d94161c3f88cbee6a586.js:1775:245)
    at t (https://canary.discord.com/assets/d94161c3f88cbee6a586.js:983:12)
    at https://canary.discord.com/assets/c0f4938da8d607f5b181.js:4157:9
    at div
    at t (https://canary.discord.com/assets/d94161c3f88cbee6a586.js:1775:245)
    at t (https://canary.discord.com/assets/d94161c3f88cbee6a586.js:983:12)
    at t (https://canary.discord.com/assets/c0f4938da8d607f5b181.js:5852:450)
    at u (https://canary.discord.com/assets/d94161c3f88cbee6a586.js:3915:679)
    at form
    at main
    at _e (https://canary.discord.com/assets/c0f4938da8d607f5b181.js:6393:562)
    at https://canary.discord.com/assets/c0f4938da8d607f5b181.js:1183:899
    at t (https://canary.discord.com/assets/d94161c3f88cbee6a586.js:1442:85)
    at ChatLayerProvider
    at t (https://canary.discord.com/assets/c0f4938da8d607f5b181.js:1026:466)
    at t (https://canary.discord.com/assets/c0f4938da8d607f5b181.js:6400:437)
    at https://canary.discord.com/assets/c0f4938da8d607f5b181.js:6405:301
    at div
    at div
    at t (https://canary.discord.com/assets/c0f4938da8d607f5b181.js:7412:845)
    at oe (https://canary.discord.com/assets/c0f4938da8d607f5b181.js:7073:972)
    at t (https://canary.discord.com/assets/d94161c3f88cbee6a586.js:494:449)
    at c (https://canary.discord.com/assets/d94161c3f88cbee6a586.js:2636:65)
    at t (https://canary.discord.com/assets/d94161c3f88cbee6a586.js:496:678)
    at div
    at div
    at div
    at div
    at n (https://canary.discord.com/assets/d94161c3f88cbee6a586.js:4592:605)
    at t (https://canary.discord.com/assets/c0f4938da8d607f5b181.js:8358:447)
    at div
    at t (https://canary.discord.com/assets/d94161c3f88cbee6a586.js:1548:958)
    at t (https://canary.discord.com/assets/c0f4938da8d607f5b181.js:8361:97)
    at ConnectedLayers
    at div
    at t (https://canary.discord.com/assets/c0f4938da8d607f5b181.js:8440:876)
    at Chat
    at t (https://canary.discord.com/assets/d94161c3f88cbee6a586.js:494:449)
    at t (https://canary.discord.com/assets/d94161c3f88cbee6a586.js:496:678)
    at n (https://canary.discord.com/assets/c0f4938da8d607f5b181.js:469:12)
    at u (https://canary.discord.com/assets/d94161c3f88cbee6a586.js:3915:679)
    at Suspense
    at d
    at t (https://canary.discord.com/assets/d94161c3f88cbee6a586.js:494:449)
    at t (https://canary.discord.com/assets/d94161c3f88cbee6a586.js:496:678)
    at div
    at A (https://canary.discord.com/assets/d94161c3f88cbee6a586.js:1906:9)
    at t (https://canary.discord.com/assets/d94161c3f88cbee6a586.js:1442:85)
    at VerificationLayerProvider
    at t (https://canary.discord.com/assets/d94161c3f88cbee6a586.js:1442:85)
    at AppLayerProvider
    at p (https://canary.discord.com/assets/d94161c3f88cbee6a586.js:2897:171)
    at t (https://canary.discord.com/assets/d94161c3f88cbee6a586.js:3771:710)
    at m (https://canary.discord.com/assets/d94161c3f88cbee6a586.js:3887:943)
    at t (https://canary.discord.com/assets/d94161c3f88cbee6a586.js:3888:436)
    at u (https://canary.discord.com/assets/d94161c3f88cbee6a586.js:3915:679)
    at Z (https://canary.discord.com/assets/d94161c3f88cbee6a586.js:5417:616)
    at t (https://canary.discord.com/assets/d94161c3f88cbee6a586.js:5792:536)
    at u (https://canary.discord.com/assets/d94161c3f88cbee6a586.js:3914:609)
    at https://canary.discord.com/assets/d94161c3f88cbee6a586.js:5706:839
    at Y (https://canary.discord.com/assets/d94161c3f88cbee6a586.js:5883:808)
    at t (https://canary.discord.com/assets/d94161c3f88cbee6a586.js:491:7)
    at t (https://canary.discord.com/assets/d94161c3f88cbee6a586.js:1014:234)
    at f (https://canary.discord.com/assets/d94161c3f88cbee6a586.js:5869:678)
_log @ VM1493 C:\Users\User\powercord\src\Powercord\plugins\bdCompat\plugins\0PluginLibrary.plugin.js:1749
```

**Comment by Strencher** [comment]
Sorry but i cannot reproduce this. It works fine on BetterDiscord.

**Comment by defoNotAnAlt** [comment]
This is my plugin list incase it helps:
```
avatar-icon-viewer
bdCompat
better-folders
Better-Friends-List
better-status-indicators
channel-typing
custom-timestamps
discord-theme-helper
discord-tweaks
DM-Typing-Indicator
f8-fix
fix-user-popouts
game-activity-toggle
guild-profile
In-app-notifs
invite-inspector
message-link-embed
message-translate
online-friends-count
open-in-app (by hellbound)
quick-mark-as-read
quick-reply (by relative)
reddit-parser
scrollable-autocomplete
show-all-activities
show-hidden-channels (by hellbound)
smart-typers
text-react
theme-toggler
twemoji-but-good
Unindent
urban
user-details
VC-Double-Click-Join
view-raw
vpc-shiki
webhook-tag
```
I have no BD plugins enabled other than UserDetails

**Comment by ObscureNightingale** [comment]
I'm unable to reproduce this issue on PowerCord with bdCompat.
Default libraries (except for bdCompat), and ZeresPluginLibrary + UserDetails plugin.

Powercord: official upstream, revision `49d2cae`, branch `v2`
UserDetails: `v2.5.0`
ZeresPluginLibrary: `v1.2.32`
OS: Monterey Beta 7 – `21A5522h`
Discord Canary: 99031 `720b494`

![image](https://user-images.githubusercontent.com/61620747/134784265-ef2ef650-7805-4080-b533-c4c699e6b5e4.png)
![image](https://user-images.githubusercontent.com/61620747/134784283-35fee759-6887-4831-9877-58a790eec3c4.png)
![image](https://user-images.githubusercontent.com/61620747/134784286-d8202df6-c65d-4062-abad-672471ad5d8e.png)

**Comment by defoNotAnAlt** [comment]
02a12eba4aa0f76a34fcddad19b8a1de6f4baf6f seems to have fixed this.
